### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by ghost** [Rympex/Pathfinding-Dijkstra#2]
If, for example, I command the bot to go from Route 2 to Route 11, it takes the Diglet Cave Shortcut, but it gets stuck if I don't have the move Cut in any of my pokemon, is there any way to work around it and just walk the long path?

Also, If I have the move Cut, it gets stuck in Digglet Cave Entrance, log is:

```
Exception Resolution:  [ Route 2 Stop3 To Digletts Cave Entrance 1 ]  GoTo  X:4 Y:12
Exception Resolution:  [ Route 2 To Digletts Cave Entrance 1 ]  GoTo  X:40 Y:96
Exception Resolution:  [ Route 2 Stop3 To Digletts Cave Entrance 1 ]  GoTo  X:4 Y:12
Exception Resolution:  [ Route 2 To Digletts Cave Entrance 1 ]  GoTo  X:40 Y:96
Exception Resolution:  [ Route 2 Stop3 To Digletts Cave Entrance 1 ]  GoTo  X:4 Y:12
Exception Resolution:  [ Route 2 To Digletts Cave Entrance 1 ]  GoTo  X:40 Y:96
Exception Resolution:  [ Route 2 Stop3 To Digletts Cave Entrance 1 ]  GoTo  X:4 Y:12
Exception Resolution:  [ Route 2 To Digletts Cave Entrance 1 ]  GoTo  X:40 Y:96
```

**Comment by Rympex** [comment]
On file Kantomap.lua u need edit:

`kanto["Route 2"] = {"Route 2 Stop2=1","Route 2 Stop3=1","Viridian City=1","Digletts Cave Entrance 1=1","Pewter City=1"}`

`Digletts Cave Entrance=1` is the node distance if u put high number instead 1, it will ignore the node

**Comment by Rympex** [comment]
https://github.com/Rympex/Pathfinding-Dijkstra/commit/60ee7c71fcedde982350135d44d1c394dd3ace23

Fixed
